core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    HomeView,
    add_to_cart,
    add_to_cart_cate,
    add_to_cart_det,
    add_to_cart_shop,
    remove_from_cart,
    ShopView,
    OrderSummaryView,
    remove_single_item_from_cart,
    CheckoutView,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    CategoryView,
    AccountView,
    CashOnDeliveryView,

    ContactView,

    SearchView)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('account/', AccountView.as_view(), name='account'),
    path('category/<slug>/', CategoryView.as_view(), name='category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart-cate/<slug>/', add_to_cart_cate, name='add-to-cart-cate'),
    path('add-to-cart-shop/<slug>/', add_to_cart_shop, name='add-to-cart-shop'),
    path('add-to-cart-det/<slug>/', add_to_cart_det, name='add-to-cart-det'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('shop/', ShopView.as_view(), name='shop'),
    path('search/', SearchView, name='search'),

    path('contact/', ContactView, name='contact'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('cod/<payment_option>/', CashOnDeliveryView.as_view(), name='cod'),
    path('request-refund/<str:ref_code>', RequestRefundView.as_view(), name='request-refund')
]

demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.utils.translation import ugettext_lazy as _


# Change admin site title
admin.site.site_header = _("All IN One")
admin.site.site_title = _("All IN One")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),

    path('', include('core.urls', namespace='core')),
    path('tinymce', include('tinymce.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
elif getattr(settings, 'FORCE_SERVE_STATIC', False):
    settings.DEBUG = True
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    settings.DEBUG = False

core/models.py
from django.core.validators import MinLengthValidator
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.
CATEGORY_CHOICES = (
    ('SB', 'Shirts And Blouses'),
    ('TS', 'T-Shirts'),
    ('SK', 'Skirts'),
    ('HS', 'Hoodies&Sweatshirts')
)

LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Slide(models.Model):
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)


class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(blank=True, null=True)
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    image1 = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    payment_received = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    payment_received = models.BooleanField(default=False)

    billing_address = models.ForeignKey(
        'BillingAddress', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    phone = models.ForeignKey(
        'BillingAddress', related_name='phone', on_delete=models.SET_NULL, blank=True, null=True)

    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a BillingAddress
    (Failed Checkout)
    3. Payment
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class BillingAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=False, blank=False)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    Phone_number = models.IntegerField(null=False, blank=False)
    Pin_Code = models.CharField(max_length=100)

    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Address'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal'),
    ('COD','Cash On Delivery')
)



class CheckoutForm(forms.Form):
    name = forms.CharField()
    Phone_number=forms.IntegerField()

    Pin_Code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))

    street_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control'
    }))
    apartment_address = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite',
        'class': 'form-control'
    }))


    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)



class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))



class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

templates/account.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}


<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
  <h2>Ordered Product</h2>
	<table id="cart" class="table table-hover table-condensed">
    				<thead>
						<tr>
							<th style="width:50%">Product</th>
							<th style="width:10%">Price</th>

							<th style="width:10%"></th>
						</tr>
					</thead>
					<tbody>
  {% for order_item in object %}
{% for items in order_item.items.all %}
						<tr>

							<td data-th="Product">

								<div class="row">
									<div class="col-sm-2 hidden-xs"><img src="{{ items.item.image.url }}" alt="..." class="img-responsive"/></div>
									<div class="col-sm-10">
										<h4 class="nomargin"><strong>{{ items.item.title }}</strong></h4>
										<h4 class="nomargin"><strong>Status:</strong>{% if order_item.refund_requested %} Refund Initated {% else %}Will Be Delivered{% endif %}</h4>
										<h4 class="nomargin"><strong>address:</strong>{{ order_item.shipping_address.street_address}}</h4>

										<h4 class="nomargin"><strong>Order No.:</strong>{{ order_item.ref_code}}</h4>
										<h4 class="nomargin"><strong>Order Date:</strong>{{ order_item.ordered_date}}</h4>

										<h4 class="nomargin"><strong>quantity:</strong>{{ items.quantity }}</h4>





									</div>
								</div>
							</td>


							<td data-th="Subtotal" class="text-center"> {% if items.item.discount_price %}
                                                                              &#8377;{{ items.item.discount_price }}
                                                                          {% else %}
                                                                              &#8377;{{ items.item.price }}
                                                                          {% endif %}</td>
							<td class="actions" data-th="">
								<button class="btn btn-info btn-sm">Print Receipt</button>
								<br><br>
                              <a href="{% url 'core:request-refund' order_item.ref_code %}">	<button class="btn btn-danger btn-sm">Request Return</button></a>
							</td>

						</tr>
                      {% endfor %}
				{% endfor %}
  </tbody>

					<tfoot>

						<tr>

							<td><a href="/" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>



						</tr>
					</tfoot>

				</table>
</div>

<style>


  .table>tbody>tr>td, .table>tfoot>tr>td{
    vertical-align: middle;
}
@media screen and (max-width: 600px) {
    table#cart tbody td .form-control{
		width:20%;
		display: inline !important;
	}
	.actions .btn{
		width:36%;
		margin:1.5em 0;
	}

	.actions .btn-info{
		float:left;
	}
	.actions .btn-danger{
		float:right;
	}

	table#cart thead { display: none; }
	table#cart tbody td { display: block; padding: .6rem; min-width:320px;}
	table#cart tbody tr td:first-child { background: #333; color: #fff; }
	table#cart tbody td:before {
		content: attr(data-th); font-weight: bold;
		display: inline-block; width: 8rem;
	}



	table#cart tfoot td{display:block; }
	table#cart tfoot td .btn{display:block;}

}
</style>
<script>
	function update_item(){
	document.getElementByTagName("input");
	}
</script>

		{% endblock content %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}

<style type="text/css">
	.selection-2{
	display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
</style>

	<!-- Title Page -->
	<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/media/{{ category_image }});">
		<h2 class="l-text2 t-center">
			{{ category_title }}
		</h2>
		<p class="m-text13 t-center">
			{{ category_description }}
		</p>
	</section>


	<!-- Content page -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						<!--  -->
						<h4 class="m-text14 p-b-7">
							Categories
						</h4>

						<ul class="p-b-54">
							<li class="p-t-4">
								<a href="/shop" class="s-text13 active1">
									All
								</a>
							</li>

							{% categories_li_a %}

						</ul>

<form class="form-inline" method="get" action="/search">
				<div class="search-product pos-relative bo4 of-hidden">

					<input class="s-text7 size6 p-l-23 p-r-50" type="text" name="search" id="search" placeholder="Search Products...">

					<button class="flex-c-m size5 ab-r-m color2 color0-hov trans-0-4">
						<i class="fs-12 fa fa-search" aria-hidden="true"></i>
					</button>
				</div>
</form>
						<!--  -->


					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->

					<!-- Product -->
					<div class="row">
						{% for item in object_list %}

						<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
							<!-- Block2 -->
							<div class="block2">
<a href="{{item.get_absolute_url}}">
								<div class="block2-img wrap-pic-w of-hidden pos-relative block2-label{{item.get_label_display}}">

									<img src="{{ item.image.url }}" alt="IMG-PRODUCT" style="height: 360px;">


								</div></a>

								<div class="block2-txt p-t-20">
									<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5">
										{{item.title}}
									</a>

									<span class="block2-price m-text6 p-r-5">

								{% if item.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="color: black;">
									&#8377;{{ item.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5">
									&#8377;{{ item.discount_price }}
								</span>
								{% else %}
								<span class="block2-price m-text6 p-r-5" style="color: black;">
									&#8377;{{ item.price }}
								</span>
								{% endif %}<a href="{% url 'core:add-to-cart-cate' item.slug %}" class="btn btn-primary" style="margin: 2px;">Add to Cart</a>
									</span>
								</div>

							</div>
						</div>
						{% endfor %}

						

						
				
				</div>
				<!-- ---- row end ------- -->

				<br>
				<!-- Pagination -->
				{% if is_paginated %}
				<div class="pagination flex-m flex-w p-t-26">
					{% if page_obj.has_previous %}
					<a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
					{% endif %}
					<a href="?page={{ page_obj.number }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{page_obj.number}}</a>
					
					
					{% if page_obj.has_next %}
					<a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
		</div>
	</section>


		{% endblock content %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Address form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}


              {{form|crispy}}


              <hr>




              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to Pay</button>

            </form>

          </div>

        </div>


          {% include "order_snippet.html" %}


      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
var hideable_shipping_form = $('.hideable_shipping_form');
var hideable_billing_form = $('.hideable_billing_form');

var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
var use_default_billing = document.querySelector("input[name=use_default_billing]");

use_default_shipping.addEventListener('change', function() {
  if (this.checked) {
    hideable_shipping_form.hide();
  } else {
    hideable_shipping_form.show();
  }
})

use_default_billing.addEventListener('change', function() {
  if (this.checked) {
    hideable_billing_form.hide();
  } else {
    hideable_billing_form.show();
  }
})

</script>
{% endblock extra_scripts %}

templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="#" class="topbar-social-item fab fa-facebook"></a>
					<a href="https://www.instagram.com/invites/contact/?i=1be694kxyb4t1&utm_content=izov7x1" class="topbar-social-item fab fa-instagram"></a>

					<a href="https://accounts.google.com/DisplayUnlockCaptcha" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
				</div>

				<span class="topbar-child1">
					Free shipping for standard order over &#8377;500
				</span>

				<div class="topbar-child2">
					<span class="topbar-email">
						<a href="">
							{% if request.user.is_authenticated %}
								{{user.email}}
							{% else %}
								<p>LogIn or Register to account</p>
							{% endif %}

					    </a>
					</span>

					<div class="topbar-language rs1-select2">
						<select class="selection-1" name="time">
							<option>INR</option>
							<option>USR</option>
						</select>
					</div>
				</div>
			</div>

			<div class="wrap_header">
				<nav class="menu">

				</nav>
				<!-- Logo -->
				<a style="text-decoration:None;" href="/" class="logo">
					<link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
					<p style="font: normal 36px 'Cookie', cursive;margin:0px;">All In <span style="color:#5383d3;">One</span></p>
				</a>
	<!-- Menu -->
				<form class="form-inline" method="get" action="/search">
				<input class="form-control mr-sm-2" type="text" placeholder="Search ...." name="search" id="search">
				<button class="btn btn-success" type="submit">Search</button>
			  </form>

				<!-- Header Icon -->
				<div class="header-icons">
					{% if request.user.is_authenticated %}

							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}

									<li><a href="{% url 'account_login' %}">Login</a></li>
										<span class="linedivide1"></span>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>

							{% endif %}

					<span class="linedivide1"></span>

					<a href="{% url 'core:account' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide1"></span>

					<div class="header-wrapicon2">
						<a href="{% url 'core:order-summary' %}" ><img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON"></a>
							<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>

						<!-- Header cart noti -->

					</div>
				</div>
			</div>


				<div class="topbar">
				<div class="topbar-social">
					<ul class="main_menu">
							<li>
								<a href="/">Home</a>

							</li>

							<li>
								<a href="/shop/">Shop</a>
							</li>

							{% categories %}
						</ul>

				</div>



			</div>

		</div>

		<!-- Header Mobile -->
		<div class="wrap_header_mobile">
			<!-- Logo moblie -->
			<a href="/" class="logo-mobile">
				<p style="font: normal 36px 'Cookie', cursive;margin:0px;">All In <span style="color:#5383d3;">One</span></p>
			</a>
	<!-- Button show menu -->
			<form class="form-inline" method="get" action="/search">

				<input style="width:170px;" class="form-control mr-sm-2" type="text" placeholder="Search ...." name="search" id="search">
				<button class="btn btn-success" style=height:40px;" type="submit"><i  class="fa fa-search"></i></button>
			  </form>
			<div class="btn-show-menu">

				<!-- Header Icon mobile -->
				<div class="header-icons-mobile">
					{% if request.user.is_authenticated %}

							<li>
								<a href="{% url 'account_logout' %}">Logout</a>
							</li>
							{% else %}

									<li><a href="{% url 'account_login' %}">Login</a></li>
										<span class="linedivide1"></span>
									<li><a href="{% url 'account_signup' %}">SignUp</a></li>

							{% endif %}

					<span class="linedivide2"></span>

					<a href="{% url 'core:account' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide2"></span>

					<div class="header-wrapicon2">
						<a href="{% url 'core:order-summary' %}">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON"></a>
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>


					</div>
				</div>

				<div style="margin-right:-15px;" class="btn-show-menu-mobile hamburger hamburger--squeeze">
					<span class="hamburger-box">
						<span class="hamburger-inner"></span>
					</span>
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">
					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<span class="topbar-child1">
							Free shipping for standard order over &#8377;500
						</span>
					</li>

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								{% if request.user.is_authenticated %}
								{{user.email}}
							{% else %}
								<p>LogIn or Register to account</p>
							{% endif %}

							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>INR</option>
									<option>USD</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fab fa-facebook"></a>
					<a href="https://www.instagram.com/invites/contact/?i=1be694kxyb4t1&utm_content=izov7x1" class="topbar-social-item fab fa-instagram"></a>

					<a href="https://accounts.google.com/DisplayUnlockCaptcha" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="/">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="/shop">Shop</a>
					</li>

					{% categories_mobile %}

				</ul>
			</nav>
		</div>
	</header>

templates/request_refund.html
{% extends 'base.html' %} 
{% load static %} 
{% load crispy_forms_tags %}
{% block content %}


<div class="container">
  <div class="row">
    <div class="col-lg-6 offset-3 mt-3">
      <h2>Request Refund</h2>
       <form method="POST">
        {% csrf_token %}


<div id="div_id_ref_code" class="form-group"> <label for="id_ref_code" class=" requiredField">
                Ref code<span class="asteriskField">*</span> </label> <div class=""> <input type="text" name="ref_code" class="textinput textInput form-control" required="" id="id_ref_code" value="{{view.kwargs.ref_code}}"> </div> </div> <div id="div_id_message" class="form-group"> <label for="id_message" class=" requiredField">
                Message<span class="asteriskField">*</span> </label> <div class=""> <textarea name="message" cols="40" rows="4" class="textarea form-control" required="" id="id_message"></textarea> </div> </div> <div id="div_id_email" class="form-group"> <label for="id_email" class=" requiredField">
       </label></div>



        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
     
    </div>
  </div>
</div>

{% endblock content %}